// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: api/omzet.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OmzetRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period string `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Outlet string `protobuf:"bytes,2,opt,name=outlet,proto3" json:"outlet,omitempty"`
	Omzet  int64  `protobuf:"varint,3,opt,name=omzet,proto3" json:"omzet,omitempty"`
}

func (x *OmzetRequestMessage) Reset() {
	*x = OmzetRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_omzet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OmzetRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmzetRequestMessage) ProtoMessage() {}

func (x *OmzetRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_omzet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmzetRequestMessage.ProtoReflect.Descriptor instead.
func (*OmzetRequestMessage) Descriptor() ([]byte, []int) {
	return file_api_omzet_proto_rawDescGZIP(), []int{0}
}

func (x *OmzetRequestMessage) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *OmzetRequestMessage) GetOutlet() string {
	if x != nil {
		return x.Outlet
	}
	return ""
}

func (x *OmzetRequestMessage) GetOmzet() int64 {
	if x != nil {
		return x.Omzet
	}
	return 0
}

type OmzetResultMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseMessage string `protobuf:"bytes,1,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
}

func (x *OmzetResultMessage) Reset() {
	*x = OmzetResultMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_omzet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OmzetResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmzetResultMessage) ProtoMessage() {}

func (x *OmzetResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_omzet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmzetResultMessage.ProtoReflect.Descriptor instead.
func (*OmzetResultMessage) Descriptor() ([]byte, []int) {
	return file_api_omzet_proto_rawDescGZIP(), []int{1}
}

func (x *OmzetResultMessage) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

var File_api_omzet_proto protoreflect.FileDescriptor

var file_api_omzet_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x6d, 0x7a, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x5b, 0x0a, 0x13, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x6d, 0x7a, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x6d,
	0x7a, 0x65, 0x74, 0x22, 0x3e, 0x0a, 0x12, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x8e, 0x01, 0x0a, 0x05, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x12, 0x42, 0x0a,
	0x0b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6d, 0x7a,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x12,
	0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_omzet_proto_rawDescOnce sync.Once
	file_api_omzet_proto_rawDescData = file_api_omzet_proto_rawDesc
)

func file_api_omzet_proto_rawDescGZIP() []byte {
	file_api_omzet_proto_rawDescOnce.Do(func() {
		file_api_omzet_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_omzet_proto_rawDescData)
	})
	return file_api_omzet_proto_rawDescData
}

var file_api_omzet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_omzet_proto_goTypes = []interface{}{
	(*OmzetRequestMessage)(nil), // 0: api.OmzetRequestMessage
	(*OmzetResultMessage)(nil),  // 1: api.OmzetResultMessage
}
var file_api_omzet_proto_depIdxs = []int32{
	0, // 0: api.Omzet.SubmitOmzet:input_type -> api.OmzetRequestMessage
	0, // 1: api.Omzet.ClearOmzet:input_type -> api.OmzetRequestMessage
	1, // 2: api.Omzet.SubmitOmzet:output_type -> api.OmzetResultMessage
	1, // 3: api.Omzet.ClearOmzet:output_type -> api.OmzetResultMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_omzet_proto_init() }
func file_api_omzet_proto_init() {
	if File_api_omzet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_omzet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OmzetRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_omzet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OmzetResultMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_omzet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_omzet_proto_goTypes,
		DependencyIndexes: file_api_omzet_proto_depIdxs,
		MessageInfos:      file_api_omzet_proto_msgTypes,
	}.Build()
	File_api_omzet_proto = out.File
	file_api_omzet_proto_rawDesc = nil
	file_api_omzet_proto_goTypes = nil
	file_api_omzet_proto_depIdxs = nil
}
